<?php
/*
Plugin Name: Order Ops
Description: Create WooCommerce orders from messy text using Groq AI.
Version: 6.7
Updated: 2026-10-07
Author: Maruf Rahman
Changelog: 6.7 - Added GET /customers/last-order so the app can show a repeat customer's previous order, which the legacy admin tool has always done over session-and-nonce-bound AJAX the app cannot use. Takes a required phone, normalized through the existing ai_normalize_bd_phone(), and 400s aioc_invalid_phone when it is not a recognizable BD mobile. An optional exclude leaves one order out, which the app needs while editing or the lookup finds the order already open on screen. A customer with no previous order returns 200 with {found: false}, deliberately NOT a 404 - "this customer is new" is a normal answer to a reasonable question, and the app shows nothing at all in that case. A found order is returned through ai_rest_prepare_order_detail(), the same builder GET /orders/{id} uses, so there is no second order shape in this API and the client already knows how to read it including line_items, shipping_lines and fee_lines. Extracted the lookup itself into ai_find_last_order_by_phone() in a new includes/orders/lookup.php, now called by both the AJAX handler and the REST route; ajax.php's response formatting is untouched because it feeds the old admin UI and expects wc_price() HTML. Trashed orders are excluded by passing no status at all, which WooCommerce treats as every valid status except those flagged exclude_from_search - that is trash and checkout-draft - rather than by passing the explicit array_keys(wc_get_order_statuses()) list GET /orders uses, because that list includes wc-checkout-draft and would surface abandoned carts as somebody's last order. The exclude id is both passed to the query and re-checked in PHP, the same defence in depth ai_rest_price_match_product_ids() applies to its price arg. ajax.php was already using ai_normalize_bd_phone() from the 5.2 refactor, so no inline normalization remained to remove.
6.6 - GET /orders now accepts status=trash so the app can show a trash view. Both 'trash' and 'wc-trash' are accepted at the boundary and normalized to the bare 'trash' for the query, because HPOS stores it unprefixed - OrdersTableDataStore::trash_order() writes 'status' => 'trash' while workflow statuses are stored prefixed - and OrdersTableQuery::sanitize_status() only adds the 'wc-' prefix when the prefixed form is a registered status, otherwise passing the value through verbatim. 'wc-trash' would therefore have reached the SQL unchanged and matched no rows, returning an empty list rather than an error. Default behaviour is unchanged: with no status param the explicit registered list is still passed and trashed orders stay out. Trash is deliberately NOT treated as a workflow status - it is WordPress's own post status, it never appears in wc_get_order_statuses() or in GET /meta, and it has no place in a filter dropdown beside Processing and Completed, whereas a custom status like wc-returned does. Also added ai_rest_order_status_label(): wc_get_order_status_name() returns the bare slug 'trash' for a trashed order, since its internal special-statuses map points wc-trash at the slug rather than at a label, so the label now falls back to the registered POST status label and a trashed order's summary reports "Trash". No label is hardcoded - it comes from whoever registered the status, the same rule the district and status lists follow.
6.5 - Two parser fixes. Leading list markers are now stripped as line prefixes in ai_normalize_text(). A bulleted message was not merely cosmetic: the marker sits between the start of the line and the field label, so the "(?:^|\n)\s*label" anchors in ai_extract_labeled_field() and ai_extract_labeled_multiline_field() stopped matching and the field was never extracted. Confirmed under a real PHP: for the reported input the name came back EMPTY from the deterministic pass, which meant ai_collect_address_candidates() was handed an empty $name and ai_remove_value_all() returned early without removing anything - that, not a failed segment match, is why the customer name leaked into the address. The bullet also survived as a bare trailing segment once the phone digits were stripped. Markers are handled in two classes: characters that can only ever be bullets (U+2022, U+00B7, U+25E6, U+25AA, U+25CF, U+25AB, U+2023, U+2043, U+2219, U+00A4) are stripped with or without a following space, while hyphen, asterisk, en dash and em dash are stripped only when a space follows, so a line beginning with a hyphen-attached number ("-\u09e7\u09e6\u09ad\u09ef", the exact shape v4.1 had to fix) keeps its sign and a hyphen inside a line ("Mirpur-10") is never touched. ai_clean_line() also trims stray bullet glyphs from either end of a segment, and a segment left holding nothing but markers or punctuation is now treated as noise. Fixing the bullets exposed a third defect and that is fixed too: ai_get_field_start_labels() was missing the multi-word phone labels, so "Phone Number:" did not register as the start of a new field and the whole phone line was absorbed into the address as a continuation line. Second fix: Tongi now resolves to Gazipur, with Kaliakair, Kapasia, Joydebpur, Konabari and spelling variants in both scripts, following the file's existing area-to-district pattern. Investigating the reported Jashore mismatch showed the fuzzy Levenshtein fallback in ai_extract_state_from_text() is the culprit class, not Tongi itself - "tongi" matches nothing at all, exactly or fuzzily - while real place names do misroute: "kishore" to Jashore, "mohakhali" to Noakhali, "sreepur" to Sherpur, "kaliganj" to Habiganj and "shibpur" to Sherpur, each at edit distance 2. Mohakhali is now an explicit Dhaka alias, which both fixes the misroute and the wrong flat shipping rate that came with it. Adding Tongi required two substring guards, because the exact pass has no word boundary and takes the first alias in insertion order: 'tongibari' (Munshiganj) and 'tungipara' (Gopalganj) are listed before it so neither starts resolving to Gazipur. Sreepur and Kaliganj are deliberately NOT added - each names an upazila in several districts - and are recorded as open items against the fuzzy matcher instead. Also backfilled the 4.8 entry that was present in this header but missing from CHANGELOG.md.
6.4 - Added fee support to the order endpoints, in both directions. The shared order response builder now returns fee_lines as [{id, name, total}], read from $order->get_items('fee'), so GET /orders/{id}, POST /orders and POST /orders/{id} all carry it. This closes a real gap: an order with a fee reported a total the client could not reconcile from line_items plus shipping_lines. A fee total CAN BE NEGATIVE - a discount is stored as a negative fee - and is passed through unchanged, with no clamping and no abs(). The name is reported exactly as stored via get_name('edit'), because the default 'view' context substitutes the word "Fee" for an empty name and runs display filters. Both write endpoints now accept fee_lines as an array of {name, total}, built with WC_Order_Item_Fee, set_name(), set_total() and $order->add_item(), applied inside the shared payload applier and therefore before ai_rest_finalize_order() so calculate_totals() counts them. Semantics match line_items exactly and independently: an absent key leaves existing fees alone, a present key removes every fee item and replaces it from the payload, and an empty array removes all fees - which DISCARDS fee item ids, since a replaced fee is a new row. An empty name is allowed and a missing or non-numeric total becomes 0, the latter with a warning, because a typo silently turning a discount into nothing is expensive. Confirmed while adding this that the two lists are genuinely independent: the line-item replacement was already scoped to get_items('line_item') and ai_apply_shipping() to get_items('shipping'), so neither disturbs fees, and nothing in this plugin calls WC_Abstract_Order::remove_order_items() with no argument, which would empty every item type at once. One WooCommerce behaviour to know about rather than a defect here: calculate_totals() caps a negative fee at the order's own value so the total cannot go below zero, and it does that by REWRITING the fee item's total, so a discount larger than the order comes back reduced rather than as sent.
6.3 - Bulk-prime the post, meta and term caches before hydrating product objects in GET /products. Measured on staging at 6.2, timing_ms was 47ms for a numeric search but 438ms for a broad text search: sorting by price needs every candidate row hydrated first, so ?search=three turned roughly 180 candidate ids into product objects one at a time, and each wc_get_product() went to the database three separate ways - get_post() for the post row, get_post_meta() for the product data, and get_the_terms($id, 'product_type') inside get_product_type(), plus product_visibility. A new ai_rest_prime_product_caches() calls _prime_post_caches($ids, true, true) once for the whole candidate window, filling all three caches in up to three queries, so the wc_get_product() calls that follow read from cache. All three flags matter: priming posts without terms would leave a term query per product in place. It is applied at every hydration loop - the price-match block, the row loop, and a variable parent's children (untestable here, no variable products, and a cache warm cannot change what is returned). _prime_post_caches() only fetches ids not already cached, so priming overlapping sets costs almost nothing. WooCommerce has no product equivalent of WC_Order_Data_Store_CPT::prime_caches_for_orders() - checked against the 11.0 code reference - and the wc_product_meta_lookup table serves the search queries rather than hydration, so priming it would warm something this loop never reads; the request-scoped product object cache added in WooCommerce 10.5 deduplicates repeat lookups of one id, which a single pass over distinct ids never does. The call is guarded with function_exists() because _prime_post_caches() was marked private before WordPress 6.1, so on an older core hydration simply reverts to the pre-6.3 behaviour. No change to the sort window, the sort order, the query structure or any response shape - timing_ms on staging is what confirms or refutes the gain.
6.2 - GET /products now orders results by price ascending instead of alphabetically by title, which was actively wrong for this catalogue: as strings "10000" sorts before "1050", so the most expensive item sat near the top of every text search. Rows are sorted by effective price, then by name using a natural comparison so embedded figures order numerically too. The sort applies WITHIN each block, never across them - an exact price match is never pushed below a cheaper substring match - and the exact-SKU row still leads everything. Added compound terms: a search containing exactly one numeric part and at least one non-numeric part returns the INTERSECTION, so "three 2500" means products called three that cost 2500, and word order is irrelevant. Two or more numeric parts fall back to treating the whole term as text rather than guessing which figure is the price; several text parts alongside one number must all match. An empty intersection returns an empty list with no silent widening, and the 3-character minimum still applies to the whole trimmed term rather than to each part. The exact-SKU lookup is skipped for compound terms, since a row admitted that way would sit outside the intersection. Added an optional fields=picker parameter that returns only id, name, sku, price and is_in_stock, omitting parent_id, stock_status, stock_quantity and thumbnail - and skipping the per-row attachment lookup entirely, for a field that is null throughout this store. The default response shape is unchanged. Added timing_ms to the envelope, wall-clock milliseconds inside the handler, to separate query work from network round-trip when the picker feels slow on mobile data. Replaced ai_rest_product_search_ids() with ai_rest_product_search_blocks(), which keeps Block A and Block B separate so each can be sorted independently; term parsing and the intersection live in their own ai_rest_parse_search_term() and ai_rest_compound_search_ids(). Still no raw SQL, the {"products": [...]} envelope key is unchanged, and the publish+private product / publish-only variation status rules are untouched.
6.1 - Added POST /token so staff log in with their ordinary WordPress username and password instead of being handed an application password. Core Basic auth only ever matches application passwords, so an account password sent that way always fails; this route verifies the account password with wp_authenticate() and then mints an application password via WP_Application_Passwords::create_new_application_password(), returning the plaintext once. The app stores that and uses Basic auth from then on - the account password is used for this one request and never stored on the device or here. Created passwords are named with a shared "Order Ops (app)" prefix plus a UTC timestamp, identifiable in wp-admin and unique because core rejects a duplicate name. This is also what sidesteps the Defender truncation defect: the plaintext is read from the return value rather than the admin display. Being the only unauthenticated route in the namespace it carries its own protection: a transient failure throttle keyed on both IP (10 per 15 minutes) and username (5), returning 429 with Retry-After; one generic 401 for every rejected credential so the route cannot be used to enumerate account names; and a manage_woocommerce check after authentication, so a valid login on an account without the capability gets a 403 rather than a credential. Passwords bypass sanitize_text_field() via a new ai_rest_sanitize_password() - the usual sanitizer would corrupt a legitimate password - and the public permission callback is the named ai_rest_permission_public() so the namespace keeps its rule that every *_callback is an ai_ function.
6.0 - Added GET /meta to the aioc/v1 namespace so the app never hardcodes a list WooCommerce owns. It returns the full BD state list in WooCommerce's own order, every registered order status with the wc- prefix stripped so the slugs match what the other endpoints accept, the store currency, the store's price decimal places, and the plugin version. Every list is read from WooCommerce at request time, so a state relabelled upstream or a status registered by another plugin appears without an app rebuild. The response is cacheable client-side for a session. Also moved ai_rest_strip_status_prefix() from orders-write.php into rest.php, since two route files now share it.
5.9 - Added the order write endpoints, completing step 4: POST /orders (create), POST /orders/{id} (partial update), POST /orders/{id}/trash and POST /orders/{id}/restore. Validation mirrors WooCommerce rather than being stricter - an empty payload creates an empty order, and only an unrecognized BD state code or order status is rejected, both with a 400. Updates are partial: only fields present in the body change, which is why POST is used rather than PUT. Supplying line_items replaces all existing product lines rather than patching them. Out-of-stock products are added anyway with a warning, since WooCommerce admin allows it, and a missing or non-orderable product id is skipped with a warning instead of failing the request. Shipping is always reapplied through ai_apply_shipping() from the single rate table. Trash uses WC_Order::delete(false) rather than wp_trash_post(), and restore reads the pre-trash status back from _wp_trash_meta_status; no force delete is reachable anywhere. Responses reuse the existing order response builder so the shape cannot drift from GET /orders/{id}.
5.8 - Added POST /parse to the aioc/v1 namespace, the first step-4 write-path endpoint - though it writes nothing. It takes raw pasted text, runs the existing ai_get_parsed_order_data() unchanged, and returns the extracted name, phone, address, state (raw text plus resolved WC code and label) and customer note, together with a shipping preview computed from the pure ai_get_shipping_rate() rate table so staff can see the cost before saving. No order is created, updated or touched. An unmatched state is not an error - it returns an empty state_code and the Outside Dhaka default rate, and the client's district dropdown resolves it. Parse failure returns 422 with the parser's own message; the parser only fails when both name and phone are missing, so partial extraction succeeds with warnings. normalized_text, raw_ai_response and the always-empty price keys are omitted to keep the mobile payload small. Also corrected a stale docblock in products.php that still called the wc_get_products() price argument unverified; staging testing at 5.7 confirmed it narrows the query.
5.7 - GET /products now searches by price, which is how staff actually look products up. A wholly numeric term first matches products whose effective current price equals it (sale price included, matching the price field in each row), then falls through to the existing name/SKU substring search; the two blocks are concatenated, deduplicated keeping the first occurrence, and the limit applies to the combined list, so price matches fill it first. Comparison is numeric, so "250" matches a stored "250.00". A non-numeric term skips the price block entirely and text search is unchanged. The price lookup is isolated in ai_rest_price_match_product_ids() and re-checks every candidate in PHP, so correctness does not depend on the unverified wc_get_products() price argument. Minimum search length raised from 2 to 3 characters.
5.6 - Fixed a fatal error that made every request to GET /products return a 500 before the handler ran. The 'limit' parameter used 'intval' as its sanitize_callback, but WordPress invokes sanitize and validate callbacks with three arguments (value, request, parameter name), and intval() accepts at most two - on PHP 8 that raises an uncaught ArgumentCountError inside WP_REST_Request::sanitize_params(). All argument callbacks in the REST layer now go through single-argument ai_rest_* wrappers defined in includes/rest/rest.php, so no bare built-in is registered as a callback anywhere. absint, sanitize_text_field and __return_true tolerate extra arguments and were not themselves broken, but are wrapped too so the pattern is uniform and greppable. Parameter clamping behaviour is unchanged.
5.5 - Fixed disabled variations being addable to orders via GET /products. A variation's post status encodes its Enabled checkbox, so 'private' there means disabled rather than inheriting the parent's visibility; the 5.4 status widening was applied too broadly and let disabled variations through. Variation checks are now publish-only via a dedicated ai_rest_variation_status_allowed(), while the wc_get_products() status argument, the parent status check and the exact-SKU path keep accepting both publish and private - that is what makes this store's private catalogue reachable.
5.4 - Fixed GET /products returning nothing on this store: the endpoint filtered to published products only, but the catalogue is kept at post status 'private' because the storefront is unused and orders are taken internally. Both 'publish' and 'private' are now accepted across every query path - the name search, the SKU search, and the variation expansion - while 'draft', 'pending' and 'trash' stay excluded. Catalog visibility is deliberately not consulted, so a product hidden from the storefront is still addable to an order. Also wrapped the response as {"products": [...]} to match the order endpoints, and made limit=0 and non-numeric limits fall back to the default of 20 instead of clamping to 1.
5.3 - Added a read-only product search endpoint to the aioc/v1 REST namespace: GET /products?search=&limit=, returning a flat list of purchasable items - one row per thing that can be added to an order. Simple products yield one row each, variable parents are excluded in favour of a row per variation (named with its attribute summary), and grouped, external and all other types are skipped. Matches product name and SKU independently, includes out-of-stock items with is_in_stock false rather than filtering them out, and restricts results to published products only.
5.2 - Added read-only order endpoints to the aioc/v1 REST namespace: GET /orders (paginated, optional search and status filters) and GET /orders/{id}, both capability-gated like the rest of the namespace. Search runs the term through the new shared phone normalizer and does an exact billing_phone lookup when it is a valid BD mobile, otherwise falls back to a customer-name search. Trashed orders are excluded and an unrecognized status slug is rejected with a 400. Every monetary value is a bare numeric string with no currency formatting or markup. Extracted the phone normalization that was inline in ajax.php into ai_normalize_bd_phone() in includes/parsing/phone.php, now shared by the AJAX lookup, the parser's phone extraction, and the REST search.
5.1 - A name repeated only in part elsewhere in the message (e.g. "Monika Sarker Moni Monika Biswas" up top and just "Monika Sarker Moni" again further down) is now recognized as a partial repeat of the already-resolved name and excluded from the address, instead of leaking in as its own address segment.
5.0 - Renamed the plugin to "Order Ops" (folder name, text domain, and ai_ function prefixes unchanged so the live site stays activated). Reorganized includes/ into parsing/, orders/, and rest/ subdirectories and moved data/bd-locations.php under includes/parsing/data/ - file moves only, no logic changes. Added a REST foundation in the aioc/v1 namespace: a permanent authenticated GET /aioc/v1/ping route for verifying auth and CORS, capability-gated on manage_woocommerce with WP core Application Passwords for auth, plus CORS headers scoped to aioc/v1 routes only and driven by a new "App Origin" setting (no wildcard fallback - an unset or mismatched origin gets no CORS grant).
4.9 - Separated order-creation logic from admin presentation and centralized shipping: order-creator.php is now output-free logic returning an order ID or WP_Error, the success/error notices and debug table moved to admin/views/creator-result.php, and the flat shipping rates (Dhaka 80, Gazipur 120, elsewhere 150) now live in a single rate table in includes/shipping.php used by both the creator and the order-edit screen hooks. Fixed orders being saved with a total of 0 - the create path never called calculate_totals(), which applying shipping now does.
4.8 - Recognized bare "Number" as a strippable phone label — it was already recognized for extracting the phone value itself, but missing from the separate list used to clean up the leftover label word, so "Number:" survived as junk in the address after its digits were stripped.
4.7 - Duplicate name/phone occurrences in the raw message (e.g. name repeated once at the top and again near the signature) are now removed everywhere they appear when building the address, instead of only the first occurrence — a leftover duplicate no longer survives as junk in the address.
4.6 - Added "টাংগাইল" (Tangail), "রাঙ্গামাটি" (Rangamati), and "চুয়াডাংগা" (Chuadanga) as alternate spellings in the state/district list — Bengali's ঙ্গ-conjunct-vs-ং-anusvara spelling variance meant these districts weren't being detected under their commonly-typed alternate spelling.
4.5 - Stopped treating a bare "location" as the address-wrapper label (it was matching inside compound sub-labels like "Location & Postal Code:" and discarding every address line before it); allowed a space/dash between the 2nd and 3rd phone digits (the one remaining rigid digit boundary in the phone regex) so numbers grouped like "০১ ৯১১ ৪৯৪৮৫১" are recognized and stripped from the address instead of leaking through or failing to extract at all.
4.4 - Recognized "M#"/"Mob#"/"Cell#"/"Ph#" as phone-label shorthand, fixing a latent bug where a label ending in punctuation (e.g. "num.", "m#") with nothing left after it could never match its trailing boundary check; normalized "P,O"/"P,S" (Post Office/Police Station shorthand) and runs of underscores used as a colon substitute so labels like "Dist__Rajshahi"/"Phone__..." are recognized instead of leaking into the address; added "district"/"dist"/"state" as strippable address labels.
4.3 - Recognized "Add"/"Add:" as an address label and "Num"/"Num:" as a phone label so they no longer leak into the address as leftover junk; added "Babu Bazar" to the Dhaka locality list.
4.2 - Recognized "Cell/Cell No/Cell Number" as a phone label; stripped the "আমি থাকি" address preamble and "আমার ফোন/মোবাইল/নাম্বার/নম্বর" filler so they no longer leak into the address; added "Mohammadia" to the Dhaka locality list; fixed the phone regex to consume "+880" even when a space separates it from the rest of the number (e.g. "+880 19 2362 1274"), so it no longer gets left behind in the address.
4.1 - Removed price detection entirely (deterministic and AI): it never appears in the input and was misreading hyphen-attached address numbers (e.g. "-১০৭৯") as prices, corrupting the address in the process.
4.0 - Fixed address parsing: leftover label junk (e.g. "নাম্বারঃ", "থানাঃ") no longer leaks into the address, numbered list markers ("1.", "2.") no longer get captured as field values, and multi-line address labels (e.g. "ঠিকানা") now capture all continuation lines instead of just the first.
3.9 - Split single-file plugin into a multi-file structure (mechanical refactor, no logic changes).
*/

if (!defined('ABSPATH')) exit;

define('AIOC_VERSION', '6.7');
define('AIOC_PATH', plugin_dir_path(__FILE__));
define('AIOC_URL', plugin_dir_url(__FILE__));

require_once AIOC_PATH . 'includes/logging.php';
require_once AIOC_PATH . 'includes/parsing/text-utils.php';
require_once AIOC_PATH . 'includes/parsing/phone.php';
require_once AIOC_PATH . 'includes/parsing/location.php';
require_once AIOC_PATH . 'includes/parsing/address.php';
require_once AIOC_PATH . 'includes/parsing/name.php';
require_once AIOC_PATH . 'includes/parsing/parser.php';
require_once AIOC_PATH . 'includes/parsing/groq-client.php';
require_once AIOC_PATH . 'includes/orders/shipping.php';
require_once AIOC_PATH . 'includes/orders/order-creator.php';
require_once AIOC_PATH . 'includes/orders/lookup.php';
require_once AIOC_PATH . 'includes/ajax.php';
require_once AIOC_PATH . 'includes/rest/rest.php';
require_once AIOC_PATH . 'includes/rest/routes/orders.php';
require_once AIOC_PATH . 'includes/rest/routes/products.php';
require_once AIOC_PATH . 'includes/rest/routes/parse.php';
require_once AIOC_PATH . 'includes/rest/routes/orders-write.php';
require_once AIOC_PATH . 'includes/rest/routes/customers.php';
require_once AIOC_PATH . 'includes/rest/routes/meta.php';
require_once AIOC_PATH . 'includes/rest/routes/token.php';
require_once AIOC_PATH . 'admin/menu.php';
require_once AIOC_PATH . 'admin/views/settings-tab.php';
require_once AIOC_PATH . 'admin/views/creator-tab.php';
require_once AIOC_PATH . 'admin/views/parse-preview.php';
require_once AIOC_PATH . 'admin/views/creator-result.php';
