/**
 * Fractional line-item quantities, limited to 2 decimal places, and the order
 * form's New order action.
 *
 * Quantities can be fractional because the Decimal Product Quantity plugin is
 * active on both sites. Before 7.1 the app clamped every quantity to a whole
 * number and the plugin (int)-cast it on both the way in and the way out, so
 * 1.5 silently became 1 - a wrong order with no error. These assertions cover
 * the app's half: the rounding rule, the input, the payload, and the places
 * the old integer assumption could quietly survive.
 *
 * The rounding cases are pinned to values PRODUCED BY RUNNING the plugin's
 * ai_rest_line_quantity() under PHP 8.3 with a float-safe stock filter, the
 * same way phone-parity pins phone.js. If the PHP rule changes, regenerate
 * them rather than editing them to pass.
 *
 * Run with `npm test` from app/.
 */

import fs from 'node:fs'
import path from 'node:path'
import { installDom, loadable, VIEW_MODULES, findNode, fire, settle, SRC } from './dom-shim.mjs'

installDom()

/** The order loaded into the form: one line whose price does not divide cleanly. */
const LOADED = {
  id: 412, number: '412', status: 'pending', status_label: 'Pending payment',
  date_created: '2026-10-08T10:00:00+06:00',
  billing: { first_name: 'A', phone: '01771160171', address_1: 'X', state: 'BD-13' },
  line_items: [{ id: 1, product_id: 9, name: 'Fabric', quantity: '1.5', subtotal: '1000.00', total: '1000.00' }],
  shipping_lines: [{ id: 2, method_title: 'Dhaka Flat Rate', total: '80.00' }],
  fee_lines: [], customer_note: '', total: '1080.00', currency: 'BDT',
}

const LIST = [
  { id: 1, number: '1', status: 'pending', status_label: 'Pending payment', customer_name: 'One', phone: '', total: '10.00', item_count: '1', date_created: null },
  { id: 2, number: '2', status: 'pending', status_label: 'Pending payment', customer_name: 'Two', phone: '', total: '10.00', item_count: '2.5', date_created: null },
  { id: 3, number: '3', status: 'pending', status_label: 'Pending payment', customer_name: 'Three', phone: '', total: '10.00', item_count: '3', date_created: null },
  { id: 4, number: '4', status: 'pending', status_label: 'Pending payment', customer_name: 'Four', phone: '', total: '10.00', item_count: '0.5', date_created: null },
]

const requests = []

globalThis.fetch = async (url, options = {}) => {
  const u = String(url)
  requests.push({ url: u, method: options.method || 'GET', body: options.body ? JSON.parse(options.body) : null })

  let payload = {}
  if (u.includes('/meta')) {
    payload = {
      states: [{ code: 'BD-13', label: 'Dhaka' }],
      statuses: [{ slug: 'pending', label: 'Pending payment' }],
      currency: 'BDT', price_decimals: 2, plugin_version: '7.1',
    }
  } else if (u.includes('/last-order')) payload = { found: false }
  else if (options.method === 'POST') payload = { order: LOADED, warnings: [] }
  else if (u.includes('/orders/')) payload = LOADED
  else if (u.includes('/orders')) payload = { orders: LIST, total: LIST.length, total_pages: 1, page: 1 }

  return {
    ok: true, status: 200, type: 'basic',
    headers: { get: () => null },
    text: async () => JSON.stringify(payload),
  }
}

const { load, cleanup } = loadable(VIEW_MODULES)
const { loadMeta } = await load('meta.js')
await loadMeta()

const q = await load('quantity.js')
const { OrderFormView } = await load('views/order-form.js')
const { OrdersView } = await load('views/orders.js')

const results = []
const check = (name, actual, expected) =>
  results.push({ name, pass: JSON.stringify(actual) === JSON.stringify(expected), actual, expected })

const byClass = (view, cls) => findNode(view, (n) => String(n.className).split(' ').includes(cls))
const byLabel = (view, label) => findNode(view, (n) => n.attributes?.['aria-label'] === label)
const saveOf = (view) => findNode(view, (n) => n.className === 'button primary' && String(n.textContent).startsWith('Save'))
const newOf = (view) => findNode(view, (n) => n.textContent === '+ New order')
const lastWrite = () => [...requests].reverse().find((r) => r.method === 'POST')

/** Type into an input the way a person does: input events, then blur. */
function type(node, text) {
  fire(node, 'focus')
  node.value = text
  fire(node, 'input')
  fire(node, 'blur')
}

async function loadedForm(extra = {}) {
  requests.length = 0
  const view = OrderFormView({ orderId: 412, onClose: () => {}, onOpenOrder: () => {}, ...extra })
  await settle(200)
  return view
}

async function saveBody(view) {
  fire(saveOf(view), 'click')
  await settle(200)
  return lastWrite()?.body
}

// ---- the rule itself, pinned to the PHP side -------------------------------
{
  // Generated by running ai_rest_line_quantity() under PHP 8.3.35 with
  // woocommerce_stock_amount set to a float-safe filter.
  const PHP = { '1': 1, '1.5': 1.5, '1.25': 1.25, '3.56': 3.56, '3.567': 3.57, '1.005': 1.01, '0.5': 0.5, '2.50': 2.5, '1,500': 1500 }
  for (const [input, expected] of Object.entries(PHP)) {
    check(`parseQuantity("${input}") agrees with PHP`, q.parseQuantity(input), expected)
  }

  // Not quantities at all. PHP stores 1 for these with a warning; the form
  // never sends them, because it falls back to the row's figure instead.
  for (const input of ['0', '-2', '0.004', 'abc', '', '   ']) {
    check(`parseQuantity("${input}") is not a quantity`, q.parseQuantity(input), null)
  }

  check('spaces are stripped, the decimal point is not', q.parseQuantity(' 1 .5'), 1.5)

  check('1 shows as "1", not "1.00"', q.formatQuantity(1), '1')
  check('1.5 shows as "1.5"', q.formatQuantity(1.5), '1.5')
  check('3.56 shows as "3.56"', q.formatQuantity(3.56), '3.56')
  check('"2.50" from the API shows as "2.5"', q.formatQuantity('2.50'), '2.5')

  check('− from 2 goes to 1', q.stepDown(2), 1)
  check('− from 1.5 goes to 0.5', q.stepDown(1.5), 0.5)
  check('− from 1 goes nowhere', q.stepDown(1), null)
  check('− from 0.5 goes nowhere', q.stepDown(0.5), null)
  check('+ carries no float noise: 2.3 + 1 is 3.3', q.stepUp(2.3), 3.3)
  check('− carries no float noise: 1.1 - 1 is 0.1', q.stepDown(1.1), 0.1)
}

// ---- a loaded fractional quantity, and a price that does not divide cleanly
{
  const view = await loadedForm()
  const qty = byClass(view, 'item-qty-input')
  const price = byClass(view, 'item-price-input')
  const total = byClass(view, 'item-total-input')

  check('the quantity is an editable input', qty?.tagName, 'INPUT')
  check('with the decimal keypad, like Price and Total', qty?.attributes?.inputmode ?? qty?.inputmode, 'decimal')
  check('a loaded 1.5 stays 1.5, not lifted to 1', qty?.value, '1.5')
  check('Price is total / quantity, shown at 2dp', price?.value, '666.67')
  check('Total is the server figure', total?.value, '1000.00')

  // Focusing Price and leaving it must not re-read the ROUNDED text - that
  // would make the total 666.67 x 1.5 = 1000.01 without anyone typing.
  //
  // The damage does not show at once - 1000.005 still DISPLAYS as 1000.00 -
  // it shows on the next quantity change, which multiplies whatever price the
  // row now holds. So that is where it is asserted.
  fire(price, 'focus')
  fire(price, 'blur', { target: price })
  type(qty, '3')
  check('after leaving Price untouched, quantity 3 makes Total exactly 2000.00, not 2000.01',
    total.value, '2000.00')

  type(qty, '3.567')
  check('a third decimal is rounded on blur', qty.value, '3.57')
  check('and Total follows the rounded quantity', total.value, '2380.00')

  const body = await saveBody(view)
  check('the payload sends the rounded quantity as a string', body?.line_items?.[0]?.quantity, '3.57')
  check('and the total on screen', body?.line_items?.[0]?.total, '2380.00')
}

// ---- unparseable and non-positive entries fall back ------------------------
{
  const view = await loadedForm()
  const qty = byClass(view, 'item-qty-input')
  const total = byClass(view, 'item-total-input')

  // Half-typed figures parse along the way; the fallback is what the row held
  // when the field was FOCUSED, not the last thing that happened to parse.
  fire(qty, 'focus')
  qty.value = '15'
  fire(qty, 'input')
  qty.value = 'abc'
  fire(qty, 'input')
  fire(qty, 'blur')
  check('unparseable text falls back to what the row held', qty.value, '1.5')
  check('and so does the total', total.value, '1000.00')

  type(qty, '0')
  check('zero is not a quantity', qty.value, '1.5')

  type(qty, '-2')
  check('nor is a negative', qty.value, '1.5')

  type(qty, '0.004')
  check('nor anything that rounds to zero', qty.value, '1.5')

  type(qty, '1,000')
  check('a thousands separator is stripped', qty.value, '1000')
}

// ---- the − and + buttons step by 1 and never reach zero --------------------
{
  const view = await loadedForm()
  const minus = () => byLabel(view, 'Decrease quantity')
  const plus = () => byLabel(view, 'Increase quantity')
  const qty = () => byClass(view, 'item-qty-input')

  check('− is enabled at 1.5', minus().disabled, false)
  fire(minus(), 'click')
  check('− from 1.5 lands on 0.5', qty().value, '0.5')
  check('and is then disabled, because 0.5 − 1 is not a quantity', minus().disabled, true)

  fire(plus(), 'click')
  fire(plus(), 'click')
  check('+ steps by 1 from a fraction', qty().value, '2.5')

  type(qty(), '1')
  check('typing 1 disables − straight away', minus().disabled, true)
  check('and 1 shows as "1"', qty().value, '1')
}

// ---- item_count in the order list -----------------------------------------
{
  const view = OrdersView({ onSignOut: () => {}, onOpenOrder: () => {}, onNewOrder: () => {} })
  await settle(500)

  const texts = []
  const walk = (node) => {
    if (!node || typeof node !== 'object') return
    if (String(node.className) === 'items') texts.push(node.textContent)
    for (const kid of node.children || []) walk(kid)
  }
  walk(view)

  check('item_count reads as the sum WooCommerce reports', texts, ['1 item', '2.5 items', '3 items', '0.5 items'])
}

// ---- New order from the form ----------------------------------------------
{
  let opened = 0
  const view = await loadedForm({ onNewOrder: () => { opened++ } })
  const button = newOf(view)
  const header = findNode(view, (n) => n.tagName === 'HEADER')
  const actions = byClass(view, 'form-actions')

  check('the form offers New order', !!button, true)
  check('it sits in the header', !!findNode(header, (n) => n === button), true)
  check('not in the save bar', !!findNode(actions, (n) => n === button), false)
  check('styled as a link, never as the primary button', button?.className, 'button link')
  check('Save is still the only primary button', saveOf(view)?.className, 'button primary')

  fire(button, 'click')
  check('a clean form goes straight to a new order', opened, 1)
}
{
  let opened = 0
  const view = await loadedForm({ onNewOrder: () => { opened++ } })
  type(byClass(view, 'item-qty-input'), '4')

  fire(newOf(view), 'click')
  check('with unsaved changes, the first tap only warns', opened, 0)
  check('and says what would be lost',
    /Unsaved changes here\. Tap New order again/.test(byClass(view, 'status-line')?.textContent || ''), true)

  fire(newOf(view), 'click')
  check('the second tap goes ahead', opened, 1)
}
{
  const view = await loadedForm()
  check('no New order button when there is nowhere to go', newOf(view), null)
}
{
  // main.js cannot be loaded here (it imports CSS and registers a worker), so
  // the two facts that matter about it are read from its source: both form
  // screens are given the action, and it resets the repeat-tap guard - from
  // an unsaved new order the route is already 'form:new', and without the
  // reset the tap would be swallowed.
  const main = fs.readFileSync(path.join(SRC, 'main.js'), 'utf8')
  check('both form screens are given New order', (main.match(/onNewOrder: showNewOrderForm/g) || []).length, 2)
  check('it resets the route before opening a blank form',
    /function showNewOrderForm\(\) \{\s*route = null\s*showOrderForm\(null\)/.test(main), true)
}

// ---- nothing in the app still assumes a whole-number quantity --------------
{
  const offenders = []
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) walk(full)
      else if (entry.name.endsWith('.js')) {
        const source = fs.readFileSync(full, 'utf8')
        // The old clamp, which lifted 0.5 to 1.
        if (/Math\.max\(1,[^)]*quantity/.test(source)) offenders.push(entry.name)
      }
    }
  }
  walk(SRC)
  check('no Math.max(1, quantity) clamp survives in src/', offenders, [])
}

cleanup()

let failed = 0
for (const result of results) {
  if (!result.pass) failed++
  console.log(
    `${result.pass ? 'PASS' : 'FAIL'}  ${result.name}` +
      (result.pass ? '' : `\n        expected ${JSON.stringify(result.expected)}, got ${JSON.stringify(result.actual)}`),
  )
}
console.log(`\n${results.length - failed}/${results.length} passed`)
process.exitCode = failed === 0 ? 0 : 1
