/**
 * app/src/phone.js must agree with includes/parsing/phone.php.
 *
 * It is a client-side mirror of ai_normalize_bd_phone(), used only to decide
 * whether a half-typed number is worth a last-order request. If the two drift,
 * the symptom is silent: lookups that should fire stop firing, or fire and get
 * a 400.
 *
 * EVERY EXPECTED VALUE BELOW WAS PRODUCED BY THE REAL PHP, not written by
 * hand - generated by running ai_normalize_bd_phone() over these inputs under
 * PHP 8.3 with mbstring. There is no PHP in CI, so this is how that parity
 * stays checkable. If phone.php changes, regenerate these rather than editing
 * them to pass.
 *
 * Run with `npm test` from app/.
 */

import { normalizeBdPhone } from '../src/phone.js'

/** @type {Array<[string, string]>} input, expected - '' means "not a valid BD mobile". */
const CASES = [
  ["01812345678", "01812345678"],
  ["8801812345678", "01812345678"],
  ["+8801812345678", "01812345678"],
  ["8801812345678", "01812345678"],
  ["801812345678", "01812345678"],
  ["1812345678", "01812345678"],
  ["01812-345678", "01812345678"],
  ["01812 345678", "01812345678"],
  ["০১৮১২৩৪৫৬৭৮", "01812345678"],
  ["+৮৮০১৮১২৩৪৫৬৭৮", "01812345678"],
  ["0181234567", ""],
  ["018123456789", ""],
  ["01112345678", ""],
  ["01212345678", ""],
  ["01312345678", "01312345678"],
  ["01912345678", "01912345678"],
  ["02812345678", ""],
  ["11812345678", ""],
  ["not a phone", ""],
  ["0", ""],
  ["", ""],
  ["  01812345678  ", "01812345678"],
  ["phone: 01812345678", "01812345678"],
  ["8801", ""],
  ["88018123456780", ""],
]

const results = []

for (const [input, expected] of CASES) {
  const actual = normalizeBdPhone(input)
  results.push({
    name: `${JSON.stringify(input)} -> ${expected === '' ? '(invalid)' : expected}`,
    pass: actual === expected,
    actual,
    expected,
  })
}

let failed = 0
for (const r of results) {
  if (!r.pass) failed++
  console.log(`${r.pass ? 'PASS' : 'FAIL'}  ${r.name}` +
    (r.pass ? '' : `
        expected ${JSON.stringify(r.expected)}, got ${JSON.stringify(r.actual)}`))
}

console.log(`
${results.length - failed}/${results.length} passed`)
process.exit(failed === 0 ? 0 : 1)
